version: '3.9'

services:
  sm_assignment:
    image: php_assignment:latest
    container_name: php_assignment
    restart: "no"
    build:
      context: ../..
      dockerfile: infra/Dockerfile
      target: local
    command:
      - /bin/bash
    entrypoint: "tail -f /dev/null"
    tty: true
    volumes:
      - ../..:/src
    working_dir: /src
    ports:
      - "7777:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    name: sm_assignment
